#!/usr/bin/env bash
# Show what the CLI prints when things are missing or wrong. Runs every case on a
# throwaway copy of the project, so the real vault, index and instructions are never
# touched, and writes the exact output to evidence/error-handling.md.
#
#   scripts/error_checks.sh
set -uo pipefail
cd "$(dirname "$0")/.."
ROOT="$PWD"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
export NO_COLOR=1

copy() {  # fresh copy of the project (sharing the venv) for one destructive case
  rm -rf "$TMP/p"; mkdir -p "$TMP/p"
  (cd "$ROOT" && tar cf - --exclude .venv --exclude .git --exclude runs --exclude evidence .) | (cd "$TMP/p" && tar xf -)
  ln -s "$ROOT/.venv" "$TMP/p/.venv"
}
case_() {  # title, directory, then the command to run
  local title="$1" dir="$2"; shift 2
  printf '\n## %s\n\n```text\n$ %s\n' "$title" "$*"
  (cd "$dir" && "$@" 2>&1 | grep -v "mel filter"; echo "[exit ${PIPESTATUS[0]}]")
  printf '```\n'
}

{
echo "# Error handling (what the CLI prints when something is missing)"
echo
echo "Generated by [\`scripts/error_checks.sh\`](../scripts/error_checks.sh) on $(date '+%Y-%m-%d %H:%M'). Each case runs on a"
echo "throwaway copy of the project; the real vault, index and instructions are untouched."
echo "\`HF_HOME\` points at an empty folder to simulate a machine where the models were never downloaded."

mkdir -p "$TMP/empty-hf" "$TMP/only-embeddings/hub"
ln -s "$HOME/.cache/huggingface/hub/models--mlx-community--bge-small-en-v1.5-4bit" "$TMP/only-embeddings/hub/"

case_ "No models downloaded: ask" "$ROOT" env HF_HOME="$TMP/empty-hf" ./wiki ask "What is goodwill?"
case_ "Embedding model present, Gemma missing: ask" "$ROOT" env HF_HOME="$TMP/only-embeddings" ./wiki ask "What is goodwill?"
case_ "No models downloaded: search still works (keywords only)" "$ROOT" env HF_HOME="$TMP/empty-hf" ./wiki search "LIFO reserve" -k 1
case_ "A source path that does not exist" "$ROOT" ./wiki ingest vault/raw/does-not-exist.txt
copy; rm -rf "$TMP/p/store"
case_ "Retrieval index missing" "$TMP/p" ./wiki ask "What is goodwill?"
copy; rm "$TMP/p/instructions/wiki-instructions.md"
case_ "Research-rules file missing" "$TMP/p" ./wiki ask "What is goodwill?"
copy; : > "$TMP/p/instructions/persona.md"
case_ "Persona file empty" "$TMP/p" ./wiki chat
copy; printf 'Caf\xe9 notes\r\rA line in MacRoman with an \xd2accent\xd3.\r' > "$TMP/p/vault/raw/Old Mac note.txt"; rm -f "$TMP/p/vault/raw/"Wikipedia*.txt
case_ "A non-UTF-8 text file that was never converted" "$TMP/p" ./wiki index
case_ "…which \`wiki convert\` then handles" "$TMP/p" ./wiki convert
case_ "Unknown command" "$ROOT" ./wiki summarize
case_ "No virtualenv" "$TMP" bash -c "mkdir -p novenv && cp '$ROOT/wiki' novenv/ && novenv/wiki status"
} | sed -e "s#$TMP#<tmp>#g" -e "s#/private<tmp>#<tmp>#g" -e "s#$ROOT#<repo>#g" > evidence/error-handling.md

echo "wrote evidence/error-handling.md"
